config_name: "Dyode test"
config_version : 0.1
config_date: 2024-11-04

dyode_in:
  ip: 10.0.0.1
  mac: b8:27:eb:89:1e:f3
dyode_out:
  ip: 10.0.0.2
  mac: b8:27:eb:b1:ff:ab

modules:
  "Partage de fichier 1":
     type: folder
     port: 9600
     in: /home/analyste/in
     out: /home/analyste/out
  "Partage 2":
     type: folder
     port: 9700
     in: /home/analyste/in2
     out: /home/analyste/out2
  "Automate Modbus 1":
     type: Modbus
     port: 9400
     ip: 192.168.1.150
     port_out: 502
     registers:
       - 0-100
       - 400-450
     coils:
       - 0-10
       - 100-110
  "Automate Modbus 2":
    type: modbus
    port: 9500
    ip: 127.0.0.1
    port_out: 503
    registers:
      - 0-10
      - 400-402
    coils:
      - 0-10
      - 100-110
  "Partage d'ecran presta":
     type: screen
     port: 9900
     in: /home/analyste/screenz
     out: /home/analyste/screenz