config_name: "File Transfer Only"
config_version: 1.0
config_date: "2024-11-13"

# Paramètres pour la communication entre les ordinateurs
dyode_in:
  ip: "192.168.1.182"  # IP de l'ordinateur d'entrée
  mac: "b8:27:eb:b1:ff:ab"
  interface: "eth1"

dyode_out:
  ip: "192.168.1.86"  # IP de l'ordinateur de sortie
  mac: "BC:24:11:26:2C:D3"
  interface: "fgeth0"

# Modules de transfert de fichiers via UDP
modules:
  file_transfer:
    type: "folder"
    in: "/home/analyste/in/"  # Répertoire d'entrée pour les fichiers à transférer
    out: "/home/analyste/out/"  # Répertoire de destination des fichiers
    port: 9000  # Port UDP pour le transfert de fichiers
    bitrate: 10  # Débit maximal en Mbps pour le transfert